version: '3'
services:
  mysql-server-80:
    image: mysql/mysql-server:8.0
    volumes:
        - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "3308:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
  dbwebapp-80:
    env_file:
      - dbwebapp.env
    environment:
      - DBHOST=mysql-server-80
    image: neumayer/dbwebapp
    ports:
      - "8085:8080"
    depends_on:
      - mysql-server-80